/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class", // 👈 thêm dòng này
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#4b432b",
        "on-tertiary": "#ffffff",
        "primary-container": "#dba39a",
        "surface": "#fcf9f4",
        "surface-container": "#f0ede9",
        "on-surface": "#1c1c19",
        "secondary-fixed-dim": "#e9c176",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#4e462e",
        "on-background": "#1c1c19",
        "surface-tint": "#80534c",
        "surface-variant": "#e5e2dd",
        "outline-variant": "#d6c2bf",
        "background": "#fcf9f4",
        "surface-container-highest": "#e5e2dd",
        "inverse-primary": "#f3b9af",
        "on-secondary-container": "#785a1a",
        "on-secondary-fixed": "#261900",
        "inverse-surface": "#31302d",
        "inverse-on-surface": "#f3f0eb",
        "surface-container-low": "#f6f3ee",
        "surface-container-high": "#ebe8e3",
        "secondary-container": "#fed488",
        "surface-bright": "#fcf9f4",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#675e44",
        "on-primary-fixed": "#32120d",
        "outline": "#837371",
        "primary-fixed": "#ffdad4",
        "on-secondary-fixed-variant": "#5d4201",
        "secondary-fixed": "#ffdea5",
        "on-secondary": "#ffffff",
        "secondary": "#775a19",
        "tertiary-fixed-dim": "#d2c6a6",
        "tertiary-fixed": "#eee2c1",
        "on-tertiary-fixed": "#211b07",
        "primary": "#80534c",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#f3b9af",
        "on-primary-fixed-variant": "#653c35",
        "surface-dim": "#dcdad5",
        "on-surface-variant": "#514442",
        "tertiary-container": "#bbb091",
        "on-primary-container": "#613832"
      },
      fontFamily: {
        headline: ["Noto Serif"],
        body: ["Manrope"],
        label: ["Manrope"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}